### ISSUE TITLE
Design a new logo for scheje

### ISSUE THREAD

**Issue by turbopape** [turbopape/scheje#16]
I would like some new logo, reflecting the unique properties of scheje, and highlighting the fact that it is built as an interpreter on top of Clojure!

You can submit your pull requests by overwriting the [Logo File - scheje-logo.jpg](https://github.com/turbopape/scheje/blob/master/scheje-logo.jpg)

**Comment by morachimo** [comment]
What about something like this? 
<img width="672" alt="screen shot 2016-09-28 at 00 01 17" src="https://cloud.githubusercontent.com/assets/3606242/18903556/bb14bcde-850e-11e6-88bf-fc92fc884d6d.png">

**Comment by turbopape** [comment]
Yes cool! Thanks!

**Comment by turbopape** [comment]
Mind opening a PR replacing the JPG  file?

**Comment by turbopape** [comment]
Thank you 👍 !
